import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
插件加速商店 (china-plugin-market) — 源码见 https://github.com/notesynchelper/china-plugin-market
*/
`;

const prod = process.argv[2] === "production";

const context = await esbuild.context({
	banner: { js: banner },
	entryPoints: ["src/main.ts"],
	bundle: true,
	define: {
		// 自更新开关：发行包默认开启（本插件不走官方审核）。
		// 需要关闭时构建前设 ENABLE_AUTO_UPDATE=false。
		"process.env.ENABLE_AUTO_UPDATE": JSON.stringify(
			process.env.ENABLE_AUTO_UPDATE || "true"
		),
		"process.env.DEV_MODE": JSON.stringify(process.env.DEV_MODE || "false"),
	},
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtins,
	],
	format: "cjs",
	target: "es2021",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "main.js",
});

if (prod) {
	await context.rebuild();
	await context.dispose();
} else {
	await context.watch();
}
